name = "RegressionTables2"
uuid = "ee7cb3fd-1e53-430d-af66-71c292f3fa61"
version = "0.7.9"
authors = ["Johannes Boehm <johannes.boehm@gmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[weakdeps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"

[extensions]
RegressionTables2CovarianceMatricesExt = "CovarianceMatrices"
RegressionTables2FixedEffectModelsExt = "FixedEffectModels"
RegressionTables2GLMExt = "GLM"

[compat]
Aqua = "0.8"
CovarianceMatrices = "0.22"
Distributions = "0.25"
FixedEffectModels = "1.9"
Format = "1.3"
GLM = "1.9"
LinearAlgebra = "1"
PrettyTables = "3"
Statistics = "1"
StatsAPI = "1.6"
StatsBase = "0.34"
StatsModels = "0.7"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
